FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive
MAINTAINER Matthias Hochsteger <matthias.hochsteger@tuwien.ac.at>
RUN apt-get update && apt-get -y install \
        ccache \
        clang occt-misc \
        clang-tidy \
        cmake \
        g++ \
        git \
        libcgns-dev \
        libglu1-mesa-dev \
        libhdf5-dev \
        libocct-ocaf-dev \
        libocct-visualization-dev \
        libocct-data-exchange-dev \
        libocct-draw-dev \
        libpython3-dev \
        libtbb-dev \
        libxi-dev \
        libxmu-dev \
        occt-misc \
        python3 \
        python3-distutils \
        python3-numpy \
        python3-pip \
        python3-pytest \
        python3-tk \
        tcl-dev \
        tk-dev

RUN python3 -m pip install pytest-check pybind11-stubgen
ADD . /root/src/netgen
