FROM ubuntu:24.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get -y install \
        ccache \
        clang occt-misc \
        clang-tidy \
        cmake \
        g++ \
        gfortran \
        git \
        libcgns-dev \
        libglu1-mesa-dev \
        libhdf5-dev \
        liblapack-dev \
        libocct-ocaf-dev \
        libocct-visualization-dev \
        libocct-data-exchange-dev \
        libocct-draw-dev \
        libopenmpi-dev \
        libpython3-dev \
        libtbb-dev \
        libxi-dev \
        libxmu-dev \
        occt-misc \
        openmpi-bin \
        python3 \
        python3-mpi4py \
        python3-numpy \
        python3-pip \
        python3-pytest \
        python3-tk \
        python3-full \
        tcl-dev \
        tk-dev

RUN python3 -m pip install --break-system-packages pytest pytest-mpi pytest-check pybind11-stubgen
